import CycleCommonality

open CycleCommonality

#print axioms CycleCommonality.karamata_pow
#print axioms CycleCommonality.rank_one_majorization_pow
#print axioms CycleCommonality.val_le_of_rankOne
#print axioms CycleCommonality.val_succ_le_of_rankOne
#print axioms CycleCommonality.trace_rankOne_sub_pow_ge
#print axioms CycleCommonality.fk_min
#print axioms CycleCommonality.fk_mono
#print axioms CycleCommonality.exists_critical
#print axioms CycleCommonality.kappa_star_mul_lt_one
#print axioms CycleCommonality.kappa_lt
#print axioms CycleCommonality.StepGraphon.tail_sum_bound
#print axioms CycleCommonality.StepGraphon.abs_lam_le_perron
#print axioms CycleCommonality.StepGraphon.spectral_reduction
#print axioms CycleCommonality.StepGraphon.lower_bound
#print axioms CycleCommonality.twoClique.violates
#print axioms CycleCommonality.commonality_iff
#print axioms CycleCommonality.exists_unique_critical
-- Graphon-level cycle densities
#print axioms CycleCommonality.trace_compList_eq_cycleIntegral
#print axioms CycleCommonality.cycleDensity_eq_integral
#print axioms CycleCommonality.l1norm_compPow_sub_le
#print axioms CycleCommonality.abs_cycleDensity_sub_le
#print axioms CycleCommonality.exists_finiteRank_sq_close
#print axioms CycleCommonality.exists_finiteRank_l1_close
#print axioms CycleCommonality.isStepKernel_of_finiteRank
#print axioms CycleCommonality.exists_stepGraphon_l1_close
#print axioms CycleCommonality.cycleDensity_of_factored
#print axioms CycleCommonality.commonality_of_stepKernel
#print axioms CycleCommonality.trace_pow_eq_sum_cycleProd
#print axioms CycleCommonality.StepGraphon.density_eq_sum
#print axioms CycleCommonality.StepGraphon.densityCompl_eq_sum
#print axioms CycleCommonality.exists_stepGraphon_of_isStepKernel
#print axioms CycleCommonality.StepGraphon.cycleDensity_eq
-- Headline
#print axioms CycleCommonality.commonality_graphon
#print axioms CycleCommonality.commonality_graphon_compl
#print axioms CycleCommonality.commonality_graphon_integral
#print axioms CycleCommonality.commonality_graphon_iff
